name: Build and Deploy
on:
  push:
    branches: ['main', 'refactor/all']
  pull_request:
    branches: ['main', 'refactor/all']
jobs:
  deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Rush Install ğŸ’¼
        run: node common/scripts/install-run-rush.js install
      - name: Rush Build ğŸ› ï¸
        run: node common/scripts/install-run-rush.js build
        env:
          RUSH_BUILD_CACHE_WRITE_ALLOWED: 1
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/browser-ui/dist # The folder the action should deploy.
          branch: main
          repository-name: jumpalong/test
          token: ${{ secrets.JUMPALONG_DEPLY_TOKEN }}
